"""Official 2027 Division B rules for every seeded event.

Summarized (not copied) from the coach-supplied Science Olympiad 2027
Division B Rules Manual, one entry per event on the portal. Each entry
fills a Topic's description, assessment_type and the five overview_*
fields the student page shows as the event's rules (see TopicOverview.tsx
and lessons._rules_passages).

The manual is the source of truth: `apply_official_rules` runs on every
startup after the per-event seeds in main.py and writes these values
unconditionally onto the top-level event rows, so an older summary built
from wiki snapshots or search snippets never survives a deploy. Rule
corrections and clarifications posted on soinc.org still apply on top of
the printed manual -- the notes below say so where a number is likely to
be clarified.

Trial events printed in the manual (Code Craze, Hydraulics, Protein
Builders) are deliberately not here: the portal only seeds the confirmed
national roster (see main._remove_unconfirmed_trial_events).
"""

from app import models
from app.db import SessionLocal

SOURCE = "Science Olympiad 2027 Division B Rules Manual"

# Keyed by the exact event name used in main.seed_official_topics.
RULES_2027: dict[str, dict[str, str]] = {
    "Anatomy and Physiology": {
        "assessment_type": "test",
        "description": "Written test or lab-practical stations on the human respiratory, digestive, and immune systems.",
        "what": "A core-knowledge event on human anatomy and physiology. For 2027 the systems are respiratory, digestive, and immune. It can run as a sit-down written test or as lab-practical stations (models, illustrations, specimens, apparatus, data to analyze).",
        "learn": "RESPIRATORY: anatomy and function, mechanisms and measures of pulmonary ventilation, breathing patterns, reading a spirogram, gas exchange and O2 transport (oxygen dissociation curves), effects of exercise and high altitude; disorders: COPD, asthma, emphysema, pneumonia, sleep apnea, cystic fibrosis. DIGESTIVE: anatomy and function, the alimentary canal and accessory organs, the four layers of the canal wall, comparing the linings of esophagus/stomach/small and large intestine, mechanical vs. chemical digestion, chemical digestion of proteins, fats and carbohydrates, effects of exercise and obesity; diseases: stomach and duodenal ulcers, digestive cancers, diarrhea, lactose intolerance, hepatitis, appendicitis. IMMUNE: organs (bone marrow, thymus, spleen, lymph nodes, skin), innate immunity (barriers, complement, Toll-like receptors, inflammation, innate cells), adaptive immunity, the immune response and allergic reactions; disorders: immunodeficiencies (HIV/AIDS, CVID, SCID), autoimmune diseases (MS, rheumatoid arthritis, Hashimoto's, Graves'), and type 1-4 hypersensitivities (anaphylaxis, urticaria, myasthenia gravis, Arthus reaction, serum sickness, contact dermatitis).",
        "assessed": "Teams of up to 2, about 50 minutes. Allowed: writing utensils, two Class II calculators, and one 8.5\" x 11\" sheet of notes (both sides, any source; may be laminated or in a sheet protector -- no affixed labels or extra sheets). High score wins; preselected questions break ties.",
        "theme_2027": "Respiratory, Digestive, and Immune systems. STATE & NATIONAL ONLY: respiratory -- tuberculosis, pulmonary edema, pleurisy, small cell and non-small cell lung cancer, pulmonary fibrosis, pneumoconiosis (silicosis, coal worker lung, asbestosis), blood chemistry and the control of respiratory rhythm; digestive -- diverticular disease, GERD, peptic ulcer disease, ulcerative colitis, Crohn's, celiac disease, and liver/pancreas function including Kupffer cells; immune -- organ transplants and rejection (allograft vs. autograft), cancer immunotherapies (antibody therapies, CAR-T), lupus, dermatomyositis, scleroderma, psoriasis/psoriatic arthritis. At State/Nationals, treatments and prevention for ALL listed diseases are fair game.",
        "notes": "Only one note sheet for three body systems -- prioritize diagrams, the disease lists, and anything easy to forget under time pressure. Practice station-style structure ID from models and pictures, not just written recall.",
    },
    "Boomilever": {
        "assessment_type": "practical",
        "description": "Build a wood-and-glue cantilever that mounts on a Testing Wall and holds a sand-filled bucket 40-45 cm out; scored on load held per gram of structure.",
        "what": "A build event: teams build one cantilevered beam or truss that hangs from a bolt on a vertical Testing Wall and supports a loading block, chain, and bucket that is filled with sand. Score combines structural efficiency with an optional Load Scored Bonus.",
        "learn": "Cantilever and truss design, tension vs. compression members, wood properties and glue-joint technique, and optimizing strength-to-weight. Know the test geometry: a 1/4-20 Connector Bolt sticks out of the wall with 3.0 cm clearance, the bucket chain must hang 40-45 cm horizontally from the wall and within 2.5 cm of the wall's center line, and the structure may only touch the wall between Contact Width Lines 4.0 cm either side of the bolt.",
        "assessed": "Teams of up to 2, about 10 minutes, Eye Protection B (Z87+), no impound. At check-in the structure is weighed (to 0.01 g) and the team submits an Estimated Load Supported (a tiebreaker). Teams then get 6 minutes to mount the structure and load sand; loading stops when it fails or time runs out. Score = Load Scored / Structure Mass, where Load Scored = Load Supported (max 15,000 g) + a 5,000 g bonus if earned. Tier 1 meets every rule; Tier 2 breaks one or more; structures that cannot hold the empty loading assembly (~1.5 kg) get participation only. Ties: lowest mass, then closest load estimate.",
        "theme_2027": "Contact-depth options: BASE -- the structure may only touch the wall above the 20 cm Horizontal Contact Depth Line (touching lower = Tier 2). BONUS -- only touch above the 15 cm line AND hold the full 15 kg to earn the +5,000 g Load Scored Bonus (failing 15 kg is not a violation, you just lose the bonus). Before sand goes in, the bottom of the Loading Block must sit above the bolt's centerline. Materials: wood bonded with adhesive only -- no size limit on individual pieces, and teams may laminate wood themselves (no plywood or other commercial laminates; wood may not be painted, coated, or soaked in glue; no adhesive tape).",
        "notes": "The only structure in the event -- no spares. Build and destructively test several iterations; the bonus is worth a lot, so decide early whether you are designing for the 15 cm bonus line. Participants must be able to answer questions about their design.",
    },
    "Botany": {
        "assessment_type": "test",
        "description": "Written or station test on plant life and general botany principles.",
        "what": "A core-knowledge event on plant biology, run as a paper-pencil test or as stations. Supervisors may provide live or preserved specimens, pictures, data, microscopes, and slides.",
        "learn": "Structure of plant cells, roots, stems, leaves, spore-forming bodies and flowers; plant growth and differentiation; transport and storage of gases, water, and nutrients. The major divisions between plant groups (algae vs. multicellular plants, monocot vs. dicot, embryophytes vs. cryptogams, woody vs. herbaceous). Plus: history of botany, basic plant genetics and reproduction, photosynthesis, differences between major taxonomic groups, paleobotany and plant evolution, plants in global energy and nutrient cycles, how animals and humans use plants, competition in plant communities, GMOs, food and plant-product production, and plant diseases -- including nutrient deficiencies and infections.",
        "assessed": "Teams of up to 2, about 50 minutes. Allowed: writing utensils, two Class II calculators, and one 8.5\" x 11\" sheet of notes (both sides, any source; may be laminated or in a sheet protector). High score wins; preselected questions break ties.",
        "theme_2027": "No narrow yearly focus -- the broad topic list above is the scope. Note that plant diseases, nutrient deficiencies, and infections ARE on the Division B list for 2027.",
        "notes": "Some older study notes (and this portal's wiki-based chapters) treat plant diseases and nutrient deficiencies as Division C-only -- for 2027 they are in scope for Division B, so add them to your prep. Station tests often use real specimens and microscope slides.",
    },
    "Circuit Lab": {
        "assessment_type": "test_practical",
        "description": "Written test on electricity and electronics plus hands-on tasks with breadboards and multimeters.",
        "what": "A lab event (not a build): a written test on electricity and electronics plus at least one hands-on task using supervisor-provided circuits, breadboards, and meters.",
        "learn": "At least one question from EACH area: history (Ampere, Coulomb, Kirchhoff, Volta, Ohm, Hertz, Boole); electric charge and fields, static electricity, Coulomb's Law; DC vs. AC sources, uses, and hazards; current, voltage, resistance, power, and energy; DC circuits -- series/parallel, open/short circuits, Ohm's Law, schematics; control devices (switches, relays, fuses, GFCIs, breakers); silicon PN junctions, diodes and LEDs; digital logic gates, truth tables, universal gate sets, Boolean expressions, De Morgan's Law, and combinational logic (multiplexers, adders). STATE/NATIONAL ONLY: Kirchhoff's Voltage and Current Laws. NOT tested: capacitance, inductance, AC circuit theory, frequency analysis, Thevenin/Norton, oscilloscopes, sequential logic, 3-phase power.",
        "assessed": "Teams of up to 2, about 50 minutes. Allowed: writing utensils, two Class III calculators, and any amount of notes on paper (binders, books, folders, tabs all fine; pages may be removed). Teams may bring a basic multimeter at the supervisor's discretion. Written test = 50-75% of the score, hands-on = 25-50%. Answers in metric with correct significant figures. Preselected questions break ties.",
        "theme_2027": "Math is capped: algebra with at most two equations, simple 2D geometry, whole-number binary and binary addition, and Boolean logic -- no trigonometry, complex numbers, matrices, or calculus. Example hands-on tasks: find a mystery resistor using only voltage readings, compute power delivered, make two LEDs equally bright, read a USB charger label and compute charge time, build a logic circuit from a truth table, troubleshoot a faulty circuit, wire a 3-way switch with SPDT switches, build a given equivalent resistance.",
        "notes": "Use Division B practice material -- Division C covers more. Hands-on time with a breadboard and a multimeter matters as much as theory; logic gates and Boolean algebra are a big part of the written test.",
    },
    "Codebusters": {
        "assessment_type": "test",
        "description": "Written cryptanalysis event: decode classical ciphers by hand, with a timed first question and bonus questions.",
        "what": "A core-knowledge event where teams decrypt ciphertext on a written (or computer-based) exam. Pages may be split up so team members can work different questions at the same time.",
        "learn": "REGIONAL cipher types: Aristocrats (K1 or random alphabet, spaces kept) and Patristocrats (K1, spaces removed, groups of 5), with or without hints; Baconian (letters, symbols, or formatting; word Baconians come with a 4+ letter crib); one Xenocrypt (Spanish, K1 English keyword alphabet); Fractionated Morse (crib of 4+ characters); Cryptarithms (base 10); Porta (key given); Complete Columnar Transposition (9 or fewer columns, with crib); Nihilist (keys given); Atbash; Caesar/shift; 5x5 Checkerboard (Polybius key given); Homophonic (crib reveals 3+ keyword letters; keyword has 4 unique letters). STATE/NATIONAL add: 1-2 Xenocrypts, Porta cryptanalysis (3+ char crib), Nihilist cryptanalysis (crib at least twice the keyword length), Checkerboard cryptanalysis (two 5-letter keywords, 5+ char crib), and Homophonic given 3+ keyword letters.",
        "assessed": "Teams of up to 3 (not 2), about 50 minutes. Bring ONLY writing utensils -- no calculators or notes. The packet includes a resource sheet (Morse table, English/Spanish letter frequencies, Porta and Atbash tables, Baconian mappings). Final Score = Exam Score + Timing Bonus + Special Bonus. Two or fewer errors earns full credit; each extra error costs 100 points (never below 0). Cryptarithm answers need zero errors for full credit. Timing Bonus on question 1 (an Aristocrat) = 2 x (600 - seconds), earned only within 10 minutes. Up to 3 Special Bonus questions (non-Aristocrat/Patristocrat/Xenocrypt) pay 150 / 400 / 750 points for 1 / 2 / 3 solved with no errors.",
        "theme_2027": "The Homophonic cipher is on the list, and at least one Special Bonus question must be a Homophonic. In Aristocrats, Patristocrats, and Xenocrypts no letter ever decrypts to itself. Crib positions are marked on the ciphertext for every crib problem except the Complete Columnar.",
        "notes": "Speed on the timed Aristocrat is worth up to ~1,200 points, so drill fast Aristocrat solving. With 3 team members, plan who takes which cipher types. No outside resources are allowed, so methods must be memorized.",
    },
    "Crime Busters": {
        "assessment_type": "test_practical",
        "description": "Forensic lab event: test evidence at the bench, analyze chromatography and crime-scene evidence, and name the culprit.",
        "what": "A lab event: given a crime scenario, evidence, and suspects, teams run tests on unknowns and other evidence, then write an analysis explaining who did it and why the other suspects did not.",
        "learn": "QUALITATIVE ANALYSIS (identify by solubility, acidity, magnetism, color, density, odor, and reagent tests). Solids: anhydrous sodium acetate, yeast, vitamin C, calcium carbonate, table salt, sugar, flour, gypsum (calcium sulfate dihydrate), cornstarch, baking soda, powdered gelatin, powdered Alka-Seltzer, white sand. Metals: aluminum, iron, zinc, magnesium, copper, tin. Liquids: lemon juice, isopropyl alcohol, 3% ammonia, water, vinegar, 3% hydrogen peroxide. POLYMERS/NATURAL MATERIALS: hair (human vs. dog vs. cat), fibers (animal vs. vegetable vs. synthetic), plastics (PETE, HDPE, non-expanded PS, LDPE, PP, PVC, PMMA -- burn results may be given, no burn tests). PAPER CHROMATOGRAPHY with Rf values. PHYSICAL EVIDENCE: fingerprint patterns (whorl/loop/arch), DNA electropherograms, shoeprints and tire treads, soil composition, spatter patterns (no calculations).",
        "assessed": "Teams of up to 2, about 50 minutes, Eye Protection C. EACH participant may bring a Class II calculator and one 8.5\" x 11\" note sheet (both sides). Teams may bring items on the Division B Chemistry Lab Equipment List only -- anything else can be confiscated with up to a 10% penalty. Goggles, apron or lab coat, skin covered neck to wrists and toes, long hair tied back. Approximate weights: qualitative analysis 50%, polymers 10%, chromatography 5%, physical evidence 10%, written crime analysis 25%. Ties: analysis, then qualitative, then polymers. Up to 10% penalty for not cleaning up.",
        "theme_2027": "Amount of evidence by level -- Regionals: 6-15 unknowns (up to 2 mixtures of 2 solids), 5-7 polymer items, 1 chromatography type, 1-2 physical-evidence topics. State: 10-18 unknowns (2-4 mixtures of 2-3 solids), 7-10 polymer items, 1-2 chromatography types, 2-3 topics. Nationals: 14-20 unknowns (2-6 mixtures), 10-15 polymer items, 1-3 types, 2-4 topics. Only the starred solids (calcium carbonate through white sand) appear in mixtures. The supervisor provides iodine reagent, 1M HCl, chromatography materials, waste containers, and distilled water.",
        "notes": "Half the points are qualitative analysis -- drill a flowchart for the 13 solids until it is automatic. The written analysis (25%) must also explain why each other suspect is NOT the culprit.",
    },
    "Disease Detectives": {
        "assessment_type": "test",
        "description": "Written test on epidemiology: surveillance, outbreak investigation, and disease control and prevention.",
        "what": "A core-knowledge event (in partnership with the CDC) on the study of disease, injury, health, and disability in populations. Questions are process-oriented: evaluating and interpreting scenarios and data, not memorizing pathogens.",
        "learn": "Three roughly equal parts. (1) BACKGROUND & SURVEILLANCE: clinical vs. public-health approach, history of epidemiology, the natural history and spectrum of disease, infectious vs. noninfectious causes, CDC glossary terms (outbreak, epidemic, pandemic, vector...), the 5-step surveillance process and surveillance-system attributes. (2) OUTBREAK INVESTIGATION: case scenarios, experimental vs. observational studies (case-control, cohort, ecological, cross-sectional), steps of an outbreak investigation, case definitions by person/place/time, epi curves, line listings, cluster maps, PFGE gels, SNP mapping and PulseNet, agent-host-environment triad and chain of transmission, attack rate, relative risk and odds ratio, Bradford Hill criteria vs. Koch's and Evans' postulates and newer causal models (DAGs, sufficient-component cause, GRADE). (3) PATTERNS, CONTROL & PREVENTION: trends in charts and tables; risk, ratio, proportion, attack rate, incidence rate, prevalence, death and mortality rates; disease control strategies; levels of prevention.",
        "assessed": "Teams of up to 2, about 50 minutes. Allowed: writing utensils, two Class II calculators, one 8.5\" x 11\" sheet of notes (both sides). Points for accuracy, reasoning, graphs/charts, calculations, and use of proper scientific methods; preselected questions break ties.",
        "theme_2027": "STATE & NATIONAL ONLY: study design, bias, error, and confounding; herd immunity; and calculating vaccine effectiveness and efficacy from experimental and observational data. Matching pathogens to diseases, symptoms, or incubation periods is explicitly NOT tested (that information may be given as background).",
        "notes": "Calculation-heavy -- practice 2x2 tables (attack rate, relative risk, odds ratio) and rate calculations until fast. Use the CDC's Principles of Epidemiology in Public Health Practice for vocabulary.",
    },
    "Dynamic Planet": {
        "assessment_type": "test",
        "description": "Written or station test on Earth's fresh waters: hydrology, rivers, groundwater, lakes, and wetlands.",
        "what": "A core-knowledge Earth-science event (with NOAA and NAAEE) on the properties and processes of Earth's fresh waters, run as an exam and/or timed stations.",
        "learn": "Hydrologic cycle fluxes, reservoirs, residence times, water budgets, and the critical zone; climatic controls (precipitation, orographic lift and rain shadows, continentality, lake effect, arid-to-humid spectrum, playas, evaporites); drainage basins, divides, stream order, drainage patterns and density; channel types (braided, meandering, straight, anastomosing) and sinuosity; sediment properties, bed/suspended/dissolved load, competence and capacity, bedforms; longitudinal profiles, base level, graded streams, knickpoints, erosional processes, and floodplain landforms (point bars, cut banks, oxbows, levees, deltas, alluvial fans); flow regimes, discharge, open-channel flow relationships, floods and recurrence intervals; groundwater zones, aquifers (confined/unconfined/artesian), porosity and permeability, hydraulic gradient, saltwater intrusion, karst; lake types, budgets, stratification and turnover, shorelines, wetlands; sedimentary structures and paleochannels; human impacts (land use, dams, levees, channelization, wells, subsidence, pollution); and measuring/monitoring (topo maps, water-table maps from well data, stream gauging and hydrographs, observation wells, tracers, remote sensing).",
        "assessed": "Teams of up to 2, about 50 minutes. Allowed: writing utensils, two Class II calculators, and one binder of any size (sheet protectors, lamination, tabs, labels OK). If the event uses lab stations with samples or displays, nothing may be removed from the binder. Points for accuracy, reasoning, and scientific method; preselected questions break ties.",
        "theme_2027": "Earth's Fresh Waters -- the full topic list above (11 areas, a through k) is the 2027 scope.",
        "notes": "A well-organized, tabbed binder is a big advantage. Expect calculations (sinuosity, discharge, hydraulic gradient, recurrence intervals) and map work (topographic maps, water-table contours, hydrographs).",
    },
    "Elastic Launched Glider": {
        "assessment_type": "practical",
        "description": "Build and trim free-flight gliders launched by an elastic launch handle; scored on the sum of the three longest flight times.",
        "what": "A build event: before the tournament, teams build, test-fly, log data on, and optimize free-flight gliders launched from a hand-held elastic launch handle, aiming for maximum time aloft indoors.",
        "learn": "Lift, drag, and stability (wing area, dihedral, center of gravity, trim), lightweight construction, elastic launch technique, and collecting and analyzing flight data to improve the glider.",
        "assessed": "Teams of up to 2, about 10 minutes, Eye Protection B. Bring up to 2 gliders, launch handle(s), flight log, tools, and a Measurement Box. Each team gets a 6-minute Flight Period for trim flights and up to 5 official flights (with 1 or 2 gliders); announce trim vs. official before each launch. Time aloft = median of (ideally) 3 timers. Final Score = sum of the 3 longest flights x flight-log bonus (x1.2 complete log, x1.1 partial, x1.0 none). Construction or competition violations rank a team below all teams without them. Ties: longest non-scored official flight.",
        "theme_2027": "Glider mass must be more than 3.5 g and less than 10.0 g throughout the flight. In flight configuration it must fit fully inside a team-provided, lidless Measurement Box whose outside fits within 32.0 x 24.0 x 47.0 cm. Blunt-nose rule: the nose pushed into a lip-balm cap (~1.57 cm deep x ~1.37 cm wide) must not touch the end. Any material except boron filament; kits may not have pre-glued joints or pre-covered surfaces. Launch handle under 1 m long, with non-metallic elastic that stays on the handle. Flight log for the bonus: 10+ test flights with peak height, relaxed elastic length, flight time, plus at least 1 more parameter of your choice, all with units.",
        "notes": "Tournaments must announce room length, width, and ceiling height in advance -- trim for that space. Gliders are fragile; bring the second glider and repair supplies. Keep the flight log complete: a 20% multiplier is easy points.",
    },
    "Experimental Design": {
        "assessment_type": "practical",
        "description": "Design, run, and write up an experiment on-site from a surprise question and materials; scored with the official checklist.",
        "what": "A lab event: teams receive an assigned question or topic and a set of identical materials, then design, conduct, and report an experiment entirely during the event.",
        "learn": "The full report: statement of the problem, hypothesis with direction and rationale, independent/dependent variables with operational definitions and levels, controlled variables, materials, a repeatable procedure with labeled setup diagrams, qualitative observations, a data table, a properly titled/labeled graph, statistics of central tendency and variation with example calculations, experimental errors and their effects, Claim-Evidence-Reasoning analysis (data trend, outliers, variation), a conclusion that restates the hypothesis, and suggestions for improvements, applications, and future experiments.",
        "assessed": "Teams of up to 3, about 50 minutes, Eye Protection C (goggles required). Teams may bring one timepiece, one linear measuring device, and one Class II calculator -- for their normal use only, never as part of the experiment. First 20 minutes: get the topic, materials, and Part I of the report form and design/run the experiment; then Part II arrives for analysis (experimenting may continue). Scored on the 2027 checklist: Part I = 51 points; Part II = 55 points (67 at State/National, which adds extra statistics, CER, and applications rows). Ties: CER, then Procedure, Variables, Data Table, Graph.",
        "theme_2027": "Multipliers: x0.95 for not cleaning up; up to x0.75 for drifting off the assigned topic; x0.25 for not collecting real on-site data or for falsified data. Unsafe behavior = disqualification.",
        "notes": "The topic is unknown in advance, so practice timed runs with the official checklist and student report form from soinc.org. With 3 people, split roles: one runs trials, one records, one starts writing.",
    },
    "Food Science": {
        "assessment_type": "test_practical",
        "description": "Dairy-focused food science: a pre-built experiment notebook, on-site dairy lab tasks, and a written test.",
        "what": "A lab event on the science of milk products. Teams submit an experiment notebook made before the tournament, complete one or more dairy lab tasks on site, and take a written test.",
        "learn": "Dairy food science only: lipids, carbohydrates, and proteins in dairy foods; labeling regulations; esterification and fat bonding; saturated vs. unsaturated fats; structures of sugars, starches, fats, and proteins; essential fats, vitamins, and proteins; how cooking changes dairy foods; allergens; preservation; RDAs of minerals and vitamins in dairy and deficiency effects; freezing point depression; non-dairy 'milks'; lactose-free, low-fat, and fat-free milk; lactose intolerance; emulsification; pasteurization; organic dairy; casein and whey; probiotics.",
        "assessed": "Teams of up to 2, about 50 minutes, Eye Protection C, impound (the notebook). Allowed: two Class III calculators per team, one 8.5\" x 11\" note sheet per participant, items on the Division B Chemistry Lab Equipment List, plus a pint zip bag, a gallon zip bag, a 500-600 mL lidded container, and ~30 cm square of cheesecloth. Lab-safety clothing required. Final Score = Notebook (max 18) + Lab Task(s) + Test (percent / 2, max 50) - penalties.",
        "theme_2027": "Milk and dairy products. NOTEBOOK: at least 3 experiments for EACH of the three lab tasks (only the first 3 per task are graded), each with one independent variable, on the Food Science Experiment Form; up to 2 points each. LAB TASKS (Regionals 1, State 1-2, Nationals 2-3): (1) Ice cream formation -- shaken-bag ice cream that must self-stand 5 seconds, 0.1 point per mm of height; (2) Curd mass -- curdle 120 mL milk with vinegar or lemon juice and drain 15 minutes in cheesecloth; (3) Milk fat mass -- shake 150 mL of ~13 C cream into butter. Curd and butter score = team mass / supervisor mass x 10 (max 10 each).",
        "notes": "The notebook is 18 easy points if done properly -- start the 9+ experiments early. Practice all three lab tasks with real milk and cream until results are repeatable.",
    },
    "Heredity": {
        "assessment_type": "test",
        "description": "Written test (possibly stations) on classical and molecular genetics with calculations and data analysis.",
        "what": "A core-knowledge event on classic and molecular genetics. Questions emphasize quantitative reasoning, calculations, interpreting experiments, and evidence-based conclusions. The topic list is exhaustive.",
        "learn": "MENDELIAN GENETICS: Mendel's laws, mono- and dihybrid Punnett squares, probability of genotypes/phenotypes, pedigree analysis (dominant vs. recessive, autosomal vs. sex-linked). MITOSIS & MEIOSIS: stages and structures, human karyotype analysis. MOLECULAR BIOLOGY OF DNA: nucleotide structure, 5'/3' directionality, base pairing, replication at the fork with proofreading, DNA organization (plasmids, chromatin, euchromatin/heterochromatin, chromosomes), mutation types and their protein effects (frameshift, silent, missense, nonsense). GENE & PROTEIN: the central dogma, transcription (initiation, elongation, termination, activators/repressors, splicing, capping, polyadenylation), translation (ribosome, mRNA, tRNA). POPULATION GENETICS: Hardy-Weinberg calculations and assumptions, drift, founder effect, bottlenecks, migration, relative fitness. TECHNIQUES: PCR (denaturation, annealing, extension, temperatures, components, uses).",
        "assessed": "Teams of up to 2, about 50 minutes. Allowed: writing utensils, two Class II calculators, one 8.5\" x 11\" sheet of notes (both sides). Written test that may be arranged in stations. Points for accuracy, reasoning, and scientific method; preselected questions break ties.",
        "theme_2027": "STATE & NATIONAL ONLY: non-Mendelian patterns (linkage, incomplete and codominance, complementation), recessive epistasis, UV damage and nucleotide excision repair, the lac operon, additive alleles and continuous variation, Sanger sequencing. NATIONALS ONLY: the trp operon.",
        "notes": "Calculation-heavy -- drill probability with dihybrid crosses, pedigrees, and Hardy-Weinberg problems. No single topic is over-weighted, so cover the whole list.",
    },
    "Hovercraft": {
        "assessment_type": "practical",
        "description": "Build event: an air-levitated, battery-powered vehicle carries nickels down a 185 cm track as close to a Target Time as possible.",
        "what": "A build event: teams design, build, and calibrate a self-propelled, air-levitated vehicle ahead of time, then run it down a railed track carrying a nickel load they choose, aiming to hit a Target Time announced at the event.",
        "learn": "Lift from an air cushion, thrust from propellers/impellers, simple DC circuits (batteries, switches, resistors, motors), weight distribution and stability, and calibrating run time vs. load with real test data.",
        "assessed": "Teams of up to 2, about 10 minutes, Eye Protection B, impound (one vehicle, spare parts, and notes; batteries stored separately). Tools and two Class III calculators need not be impounded. Each team gets 8 minutes for adjustments and up to 2 runs (no practice runs). Final Score = best Run Score = Distance Score (40 for a complete run, prorated otherwise) + Time Score (40 x (1 - |run time - TT| / TT)) + Mass Score ((4 x rolls + 0.1 x loose nickels), prorated by distance, max 20). A run is incomplete if the vehicle stops for 3 seconds or does not finish within 2 x TT. Optional ramp: Distance Score x0.5 and Mass Score = 0 for that run. Multipliers: x0.7 for missing impound, x0.8 per construction violation, x0.9 per competition violation.",
        "theme_2027": "Target Time 6.0-18.0 s (1.0 s steps at Regionals, 0.5 s at State/Nationals), the same for all teams. Vehicle must fit a 40.0 cm cube when levitated and carry a 1/4\"+ wooden dowel within 3.0 cm of its front edge reaching at least 20.0 cm above the track (it triggers the timing). Electrical parts limited to batteries, wires, mechanical switches, relays, resistors/potentiometers, capacitors, and up to 2 motors; no integrated circuits, no lasers. Commercial batteries with original labels only, no lithium or lead, max 12.0 V. All propellers shielded so a 3/8\" dowel cannot touch them; manual on/off switch required. Track: 45.0 cm wide, 185.0 cm timed length. Mass: 4 full nickel rolls (~200 g), 1 half roll, and 20 loose nickels supplied -- no tape or adhesive allowed to hold them.",
        "notes": "Failing the safety rules (shielding, batteries, switch) means participation points only, so build them in from the start. The Time Score is the biggest lever -- practice hitting different target times with different nickel loads, and record that data in the impounded notes.",
    },
    "Meteorology": {
        "assessment_type": "test",
        "description": "Written or station test on Severe Weather & Storms, heavy on interpreting maps, radar, satellite, and data.",
        "what": "A core-knowledge event (with NOAA and NAAEE) on severe weather: what causes, drives, and influences it, with at least half of the questions built on interpreting weather data in maps, graphs, images, charts, or tables.",
        "learn": "Observation tools (ASOS, mesonets, radiosondes, buoys, Doppler radar products, aircraft, water-vapor/visible/IR satellite); surface maps, station models, METAR decoding, hodographs, computer models, Stuve diagrams; large-scale circulation, jet streams, stability, air masses, fronts, wind shear, atmospheric rivers, drylines; ocean and lake influence; topography; severe-weather clouds; droughts and heat waves; precipitation types and formation (hail, sleet, freezing rain, collision-coalescence, Bergeron process); floods, debris flows, mudslides; lightning; thunderstorm types (single, multicell, supercell, MCC); straight-line winds, downbursts, microbursts, gust fronts, squall lines, derechos; tornadoes and waterspouts (F and EF scales, hook echo, bow echo, TVS, debris ball); hurricanes (life cycle, structure, Saffir-Simpson, storm surge, ENSO); blizzards, nor'easters, lake-effect snow, ice storms; hazards; and NWS watches/warnings and safety actions.",
        "assessed": "Teams of up to 2, about 50 minutes. Allowed: writing utensils, two Class II calculators, and one three-ring binder of any size (contents on the rings; sheet protectors, lamination, tabs OK). Teams are expected to have a U.S. map with state names in the binder. Written exam or timed stations (no returning to earlier stations; nothing removed from the binder). Points for accuracy, reasoning, and scientific technique; preselected questions break ties.",
        "theme_2027": "Severe Weather & Storms. STATE & NATIONAL ONLY: Skew-T diagrams, Lifting Condensation Level (LCL), CAPE, and intensity-duration-frequency (IDF) curves and return periods. Historic cases (interpret data, no memorizing): hurricanes Galveston 1900, Andrew 1992, Katrina 2005, Sandy 2012, Ida 2021, Ian 2022, Hilary 2023, Helene 2024, Erin 2025, Melissa 2025; Blizzard of March 1888; the 1930s Dust Bowl; Xenia, Ohio tornado 1974 and the April 2011 outbreaks; Great Flood of 1993; Storm of the Century (March 1993). Data analysis preferably from 2022-2027.",
        "notes": "Resources are limited to a three-ring binder this season (not loose notes or folders). Practice reading radar velocity and reflectivity images, soundings, and hodographs -- data interpretation is at least 50% of the test.",
    },
    "Ping Pong Parachute": {
        "assessment_type": "practical",
        "description": "Build up to two air-pressure bottle rockets that launch a ping pong ball on a parachute; scored on the longest time aloft.",
        "what": "A build event: teams build up to two bottle rockets before the tournament and launch a ping pong ball on a parachute from a supervisor-provided air launcher, trying to keep the parachute payload aloft as long as possible.",
        "learn": "Parachute drag and descent rate, rocket stability (fins, nose shape, center of pressure vs. center of mass), how launch pressure affects height, and using flight data to choose a pressure that maximizes hang time without hitting the ceiling.",
        "assessed": "Teams of up to 2, about 5 minutes, Eye Protection B. Bring up to two rockets, two unaltered standard ping pong balls, two parachutes, and a practice log; you may bring a manual bicycle pump with gauge that fits the supplied Schrader-valve launcher. Teams get 5 minutes for 2 launches. Score = longest time aloft (middle of 3 timers) from a single launch; the other launch breaks ties. Multipliers: x0.90 if the payload does not separate from the rocket, x0.25 if anything hits the ceiling on the way up, x0.85 for an incomplete practice log, x0.70 for no log.",
        "theme_2027": "Rocket pressure vessel: one 1-liter-or-smaller plastic carbonated-beverage bottle, unaltered (no cutting, sanding, hot or super glue, spray paint), label presented. Attach fins and parts with TAPE ONLY, at least 5 cm above the bottle opening; no metal anywhere; no Mylar. Nose must be blunt (a bottle cap placed on it must not touch the nose's tip). Air pressure from the pump is the only energy source -- no water. Parachutes attach to the ball with tape only. PRACTICE LOG: 10+ test flights recording pressure (psi), estimated peak height (feet), and time aloft (seconds) plus at least two more parameters; teams use it to justify their launch pressure, and teams without a complete log are capped at a supervisor-set safe pressure.",
        "notes": "Ceiling height is announced ahead of time (over 20 ft recommended) -- tune your pressure to that ceiling, since a ceiling strike costs 75% of the launch. Keep the practice log complete.",
    },
    "Remote Sensing": {
        "assessment_type": "test",
        "description": "Written or station test on remote-sensing principles and interpreting satellite imagery of Earth (Observable Earth).",
        "what": "A core-knowledge event (sponsored by IEEE GRSS) on how remote sensing works and how to interpret imagery, data, and maps of Earth. It emphasizes concepts and interpretation over advanced math.",
        "learn": "CONCEPTS (25-35% of points): properties of light (EM spectrum, reflection, refraction, absorption, scattering, polarization, irradiance/radiance); passive sensors (UV, visible, NIR, SWIR, thermal IR) and active sensors (radar backscatter, SAR, basic InSAR, radar altimetry, radar elevation products); orbits (LEO, MEO, HEO, polar/non-polar, geostationary, geosynchronous); spatial, temporal, radiometric, and spectral resolution; instruments (scanners, multispectral imagers, radiometers, radar altimeters, thermal imagers, SAR, DEMs). INTERPRETATION (65-75%): map fundamentals (marginal info, natural/false color, thermal, radar, elevation, contours, classified maps, measuring distance, area, slope); Earth observation (aerosols, albedo and surface temperature, subsidence, vegetation change, volcanoes, landslides, floods, wildfires, glaciers, fluvial processes); supervised/unsupervised classification and the NLCD Land Cover Change Index; habitat loss, urbanization, deforestation, damage assessment.",
        "assessed": "Teams of up to 2, about 50 minutes. Allowed: writing utensils, two Class II calculators, two protractors, two rulers, and one three-ring binder of any size (contents on the rings; nothing removed during station rotations). Exam and/or timed stations. Preselected questions break ties.",
        "theme_2027": "'Observable Earth.' Imagery only from Landsat 5-9 (TM, ETM, OLI), Sentinel-1A/1B, Sentinel-2A/2B, Terra (MODIS, ASTER), SRTM, ECOSTRESS, and GOES. Equations are limited to Wien's law, c = wavelength x frequency, Snell's law, the inverse-square law, Stefan-Boltzmann, radar altimetry range, and Kepler's third law -- and only Wien's law, the wave equation, and radar altimetry range may be calculated; the rest are qualitative.",
        "notes": "Most points come from interpreting images, so practice with real Landsat and Sentinel band combinations (true vs. false color, thermal, radar). Shares map-reading skills with Dynamic Planet and Meteorology.",
    },
    "Rocks and Minerals": {
        "assessment_type": "test",
        "description": "Station-based identification of rocks and minerals from the 2027 National List, plus questions on how they form and are used.",
        "what": "A core-knowledge event: teams identify and classify rock and mineral specimens and show how they explain geologic processes, Earth history, natural resources, and human use. Usually timed stations.",
        "learn": "MINERALS: definition; physical properties (color, hardness, luster, streak, cleavage/fracture, specific gravity/heft, diaphaneity, tenacity); other properties (acid reaction, fluorescence, magnetism, smell, taste, double refraction, piezoelectricity, radioactivity); listed crystal habits; chemical formulas and trace-element color; polymorphs; mineral families and groups; formation environments; Bowen's Reaction Series; uses including gemstone varieties (emerald, aquamarine, morganite, kunzite, hiddenite, peridot, ruby, sapphire, pearl, amber). ROCKS: definition; classification; igneous textures, felsic-to-ultramafic composition, intrusive vs. extrusive, plate-boundary settings; sedimentary textures, grain size and sorting vs. energy, depositional environments, sedimentary structures; metamorphic foliation, index minerals, protoliths, regional vs. contact metamorphism, metamorphic grade; the rock cycle; economic uses.",
        "assessed": "Teams of up to 2, about 50 minutes. Allowed: writing utensils, one Class II calculator, one magnifying glass, one three-ring binder of any size, one commercial field guide (may be tabbed and annotated), and one annotated copy of the 2027 National Rocks and Minerals List (it need not be in the binder). No samples may be brought. At stations you cannot return to a previous station and nothing but the list may be removed from the binder. Identification is 30-50% of points; rock and mineral questions are balanced. No HCl is provided and no taste tests.",
        "theme_2027": "Identification is limited to the 2027 National Rocks and Minerals List; specimens marked with an asterisk are State/National only. List notes: bauxite is now classed as a sedimentary rock; pink/tan potassium feldspar is identified as Orthoclase/Microcline; 'tourmaline' is accepted for the group; Rock Salt = Halite and Rock Gypsum = Gypsum for ID purposes.",
        "notes": "Handle real specimens -- photos are not enough. Annotate the official list with key ID features, and use the binder for formation, uses, and classification charts.",
    },
    "Roller Coaster": {
        "assessment_type": "practical",
        "description": "Build a gravity-powered ball track with elevators and a loop that runs as close to a Target Time (30-60 s) as possible.",
        "what": "A build event: teams build a roller-coaster track that guides a ball using only its starting gravitational potential energy, aiming to finish as close as possible to a Target Time revealed at the event, while earning points for a compact size, lift 'elevators', and a loop.",
        "learn": "Energy conservation, friction and speed control, simple machines and mechanical advantage (levers, wheel and axle, pulleys, IMA), loop dynamics, and tuning run time quickly and repeatably.",
        "assessed": "Teams of up to 2, about 12 minutes, Eye Protection B, impound (track, balls, tools, spare parts, notes). Teams get 8 minutes to set up, make unlimited practice runs, and up to 2 declared scorable runs. Final Score = better Run Score = Size Score + Time Score + Elevator Score + Loop Score. Size Score = (60 - height) + (30 - width) + (80 - length) in cm. Time Score = 5 points per full second up to the Target Time, minus 5 per full second past it (up to 2 x TT); a ball that does not cross the finish gets a Time Score of 0. Elevator = 50 points per type that works; Loop = 3 points per cm of loop height. Tier 2 for any violation, Tier 3 if not impounded. Ties: Loop, Size, Time score, then longest run.",
        "theme_2027": "Target Time 30-60 s (5 s steps at Regionals, 2 s at State, 1 s at Nationals), revealed just before set-up. Device max 30.0 cm wide x 80.0 cm long x 60.0 cm high (excluding the ball). Ball at least 1 cm diameter, always visible, released by pulling a supervisor-provided #2 pencil. No magnets, electronics, springs, or rubber bands. Up to 2 elevator types: Type 1 = first-class lever + wheel and axle, Type 2 = second-class lever + pulley, each with IMA under 1 and lifting the ball at least 10 cm. One optional loop: an open (not fully enclosed) concave track that self-intersects; the ball must stay on the track, unsupported from below at the top. Exactly one labeled Start Line and Finish Line, fixed after impound, and a mechanism that safely stops the ball.",
        "notes": "Time and loop points are large; size points reward a compact build. Practice fast, repeatable timing adjustments for any target from 30 to 60 s.",
    },
    "Scrambler": {
        "assessment_type": "practical",
        "description": "A falling-mass-powered vehicle carries a raw egg 7-10 m and stops at a Terminal Barrier without breaking it; low score wins.",
        "what": "A build event: a mechanical device powered only by a falling mass (up to 2.00 kg) launches a vehicle carrying a raw egg along a track, aiming to stop the egg tip as close as possible to the center of a Terminal Barrier, quickly, and without breaking it.",
        "learn": "Turning gravitational potential energy into vehicle motion, gearing and linkages, friction, automatic braking and distance-setting mechanisms, aiming, and protecting a fragile payload.",
        "assessed": "Teams of up to 2, about 12 minutes, Eye Protection B, impound before the first time slot (Scrambler, spare parts, alignment devices, papers, falling mass detached). Class III calculator allowed. 8-minute Event Time for up to 2 runs. LOW score wins. Run Score = 100 + 2.0 x Vehicle Distance (cm from egg tip to the Target Point) + Run Time (s) + Can Bonus + penalties. Can Bonus = -0.5 x (110 - Inside Can Distance) for driving between two cans on the Bonus Line. Penalties: +150 competition violation, +300 construction violation, +50 for an unmodified kit. A Failed Run scores 2,500 distance points. Not impounded: +5,000. Final Score = the better run.",
        "theme_2027": "Target Distance 7.00-10.00 m (0.25 m steps at Regionals, 0.10 m at State, 0.01 m at Nationals), announced after impound. Whole Scrambler (with egg, falling mass, and floor cushion) fits a 100.0 x 50.0 cm base x 100.0 cm high box; the falling mass may never touch the floor. Stopping must be automatic and inside the vehicle; no electronics, remote control, or tethers. Egg mount: wooden backstop 5.0 x 5.0 cm, at least 1.1 cm thick (no balsa), with two 1/4\"-3/8\" dowels sticking out 3.0-4.0 cm, their bottoms 5.0-10.0 cm above the track; the egg is the vehicle's foremost point and is taped on by the team. Start by actuating with an unsharpened #2 pencil. Kits allowed with at least 2 documented functional modifications (Kit Modification Form, impounded). Breaking the egg, touching the barrier with anything but the egg, or the egg tip passing the barrier's front are violations.",
        "notes": "Distance costs 2 points per cm, so stopping accuracy beats speed. Practice with real eggs, and practice placing the inside can -- the closer it is to the outer can, the bigger the bonus.",
    },
    "Solar System": {
        "assessment_type": "test",
        "description": "Written test on habitability within and beyond the Solar System; two note sheets, no calculator.",
        "what": "A core-knowledge event on habitability in and beyond the Solar System. Exams emphasize mathematical reasoning, concepts, and interpreting data in maps, graphs, images, charts, and tables -- not trivia.",
        "learn": "OBJECTS: Venus, Mars, Ganymede, Europa, Enceladus, Titan, Makemake, asteroid 101955 Bennu, comet 67P/Churyumov-Gerasimenko, and the exoplanet systems TRAPPIST-1, Kepler-452, and LHS 1140 (Solar System objects weighted more heavily). TOPICS: conditions for habitability (temperature, atmosphere and its retention, stable surface/subsurface liquids, tidal heating, chemical disequilibrium); geologic and chemical evidence (past water from landforms, composition from spectra, delivery of water and organics by small bodies); basic biology and chemistry (building blocks of life, forms of water and ice, brines, clathrates, extremophiles); exoplanet detection by transits, radial velocity, microlensing, and direct imaging; spacecraft and telescope design for Venus Express, DAVINCI, VERITAS, Perseverance, MRO, MAVEN, Galileo, Europa Clipper, JUICE, Cassini-Huygens, Dragonfly, OSIRIS-REx, Rosetta, Kepler, JWST, and Roman. MATH without a calculator: Doppler shift, flux and inverse-square law, albedo, Stefan-Boltzmann, Wien's law, equilibrium temperature, kinetic and potential energy, Newton's gravitation, Kepler's laws, escape velocity, tides, ideal gas law, Arrhenius kinetics, chemical (dis)equilibrium.",
        "assessed": "Teams of up to 2, about 50 minutes. Allowed: writing utensils and two 8.5\" x 11\" sheets of notes (both sides; may be laminated or in a sealed sheet protector; no labels). Calculators are NOT allowed -- math is algebra, estimation, dimensional analysis, proportions, and sketching graphs. Points for quality and accuracy; preselected questions break ties.",
        "theme_2027": "Habitability within and beyond the Solar System. Exams should not include detailed questions on objects or missions not on the lists above.",
        "notes": "Because there is no calculator, practice order-of-magnitude estimates and rearranging formulas by hand. Put each listed object's key habitability facts on the note sheets.",
    },
    "Thermodynamics": {
        "assessment_type": "test_practical",
        "description": "Build a device that collects heat from a heat lamp to warm a cup of water, predict its final temperature, and take a written test.",
        "what": "A build/lab event: teams bring a pre-built device that gathers heat from a supervisor-provided heat lamp to warm 100 mL of room-temperature water in a clear plastic cup, predict the final water temperature, and take a written test on thermodynamics.",
        "learn": "At least 3 questions from EACH area: thermodynamic systems, intensive vs. extensive properties, temperature, the zeroth law, temperature scales and conversions, heat units; phases of matter, phase changes and diagrams, latent vs. sensible heat, ideal gas law; heat transfer (conduction, convection, radiation), thermal conductivity, heat capacity, specific heat; processes (adiabatic, isothermal, isochoric, isobaric), cycles, engines, efficiency, first and second laws; history (Kelvin, Joseph Black, Joule, Carnot, Planck, Clausius, Boltzmann, Maxwell). STATE/NATIONAL ONLY: radiant exitance, blackbody radiation, Stefan-Boltzmann law, third law. Math is limited to arithmetic, single-variable algebra, and simple area/volume -- no trig or calculus.",
        "assessed": "Teams of up to 2, about 50 minutes, impound (device and spare parts, at room temperature). Allowed: writing utensils, two Class III calculators, any amount of notes on paper, tools, and prepared graphs/tables for predictions. Device test: 3 minutes to set up, 1 minute to insert the cup, then the lamp heats for the Heating Time (hands off), and the team submits a predicted final temperature in C before time ends. Final Score (max 100) = Exam Score (50 x your test / top test) + Temperature Score (30 x your temperature gain / top gain) + Prediction Score (20 x your prediction accuracy / top accuracy). Multipliers on TS and PS: x0.7 per construction violation, x0.9 per competition violation. Ties: TS, then exam, then preselected questions.",
        "theme_2027": "NEW device task for 2027 -- heat COLLECTION, not insulating hot water. Lamp: a 100-125 W clear (not LED/halogen/ceramic) heat bulb in a clamp lamp with metal reflector, pointing down at the table. Bulb height: 40-50 cm at Regionals, 40-55 cm at State (5 cm steps), 40-65 cm at Nationals (1 cm steps). Heating Time: 10 minutes at Regionals, 10-15 minutes at State/Nationals. Water: 100 mL in a 9 oz clear plastic party cup supplied by the supervisor. Device with cup must fit a 30.0 cm cube; parts may be inside the cup but must not touch the water; nothing added to the water. Not allowed: energy sources of any kind, thermometers or probes, thermoses, coolers, vacuum-sealed parts, and hazardous materials (asbestos, mineral wool, fiberglass). Parts must start at room temperature.",
        "notes": "Older Thermodynamics material (and the 'Keep the Heat' insulated-beaker task) describes a different device -- don't build to it. Test your device under a real heat lamp at several heights and heating times, and build a prediction table from that data to bring to the event. The deep-dive chapters in this topic cover the written test, which is largely unchanged.",
    },
    "Water Quality": {
        "assessment_type": "test_practical",
        "description": "Test on marine and estuary environments, coral reef organisms, and water monitoring data, plus a student-built salinometer.",
        "what": "A core-knowledge event with a small build piece: teams are tested on marine and estuary aquatic environments, using scenarios with macroinvertebrate and water-quality data, and demonstrate a salinometer/hydrometer they built.",
        "learn": "PART I, MARINE & ESTUARY ECOLOGY (30%): aquatic ecology, water cycle, nutrient cycling, aquatic chemistry, drinking-water and wastewater treatment, food webs, community interactions, population dynamics, watersheds; plus estuaries, watershed management, sedimentation, harmful species, recently killed coral, harmful algal blooms, emerging contaminants (medicines, PFAS), and the five ocean garbage patches. PART II, CORAL REEF ID (30%): reef ecology, threats to reefs, and common-name ID, ecology, life cycles, and feeding of the listed reef organisms (e.g., banded coral shrimp, butterflyfish, crown-of-thorns starfish, fleshy algae, grouper, hard corals, lobsters, Diadema urchins, moray eels, parrotfish, pencil urchins, sea cucumbers, snapper, demosponges, sweetlips, tritons; Indo-Pacific: barramundi cod, bumphead parrotfish, giant clams, humphead wrasse; Atlantic: flamingo tongue snail, gorgonians, Nassau grouper). PART III, WATER MONITORING (30%): interpreting salinity, pH, phosphates, turbidity, dissolved oxygen, temperature, nitrates, fecal coliform, total solids, BOD, and aragonite saturation data and how they relate (no lab tests performed).",
        "assessed": "Teams of up to 2, about 50 minutes, Eye Protection C during salinometer testing. Allowed: writing utensils, two Class II calculators, one 8.5\" x 11\" sheet of notes (both sides), and one student-built salinometer/hydrometer. PART IV, SALINOMETER (10%): 5% for bringing one, 5% for an accurate reading. Preselected questions break ties.",
        "theme_2027": "Marine and estuary environments (not freshwater) with coral reefs as the ID focus. Salinometer must measure 1-10% (mass/volume) saltwater in a 400-600 mL beaker filled with at least 400 mL; estimate to the nearest 0.1%; full credit within +/-1% at Regionals and +/-0.5% at State/Nationals. A simple electronic salinometer is allowed, but nothing programmable or WiFi-capable, and no laptops or tablets.",
        "notes": "Freshwater-focused study guides from earlier seasons only partly apply -- reorient to marine/estuary content and coral reef organism ID. Build and calibrate the salinometer early against known salt solutions.",
    },
    "Write It Do It": {
        "assessment_type": "practical",
        "description": "One partner writes instructions for building an object; the other builds it from the writing alone.",
        "what": "A communication event: one participant studies an object (the same for all teams) and writes a description of it and how to build it; the partner, who never sees the object, builds it from that description.",
        "learn": "Precise technical writing, spatial vocabulary (orientation, position, connection), consistent naming of parts, step ordering, and careful literal reading.",
        "assessed": "Teams of exactly 2, about 50 minutes. The writer brings a writing utensil -- no other materials or resources. Writer: 25 minutes (no advantage to finishing early), and may not touch the object unless allowed. Builder: 20 minutes. Each piece scores for correct size, color, location, orientation, and connection; correct connections past a wrong one still count, and unused parts are not penalized. Build time breaks ties.",
        "theme_2027": "No drawings or diagrams. Numerals, words, single letters, abbreviations (no need to define them), and editing, punctuation, or scientific symbols are allowed. Drawing a subsection = Tier 2; drawing the whole model = disqualification. Objects may use science materials, inexpensive materials (straws, push pins, foam balls, paper cups, craft sticks), or construction sets (K'nex, Tinker Toys, LEGO, Lincoln Logs), and supervisors try to use different materials than the previous year.",
        "notes": "Agree on a shared vocabulary in advance (naming pieces, directions, reference points) and practice with many kinds of building materials.",
    },
}


def apply_official_rules() -> None:
    """Write RULES_2027 onto every matching top-level event row. Runs on
    every startup; idempotent. Only touches the rules fields (description,
    assessment_type, overview_*), never resources, chapters, or a coach's
    sub-topics."""
    db = SessionLocal()
    try:
        for name, rules in RULES_2027.items():
            topic = (
                db.query(models.Topic)
                .filter(models.Topic.name == name, models.Topic.parent_topic_id.is_(None))
                .first()
            )
            if topic is None:
                continue
            topic.description = rules["description"]
            topic.assessment_type = rules["assessment_type"]
            topic.overview_what = rules["what"]
            topic.overview_learn = rules["learn"]
            topic.overview_assessed = rules["assessed"]
            topic.overview_theme_2027 = rules["theme_2027"]
            topic.overview_notes = rules["notes"]
        db.commit()
    finally:
        db.close()
